src/main/java/ru/javabegin/training/library/jsfui/controller/UserController.java
package ru.javabegin.training.library.jsfui.controller;

import com.google.common.base.Strings;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.util.ResourceBundle;

@ManagedBean
@ViewScoped
@Component
@Getter @Setter
public class UserController  {

    private String username;
    private String password;

    // для вывода данных о пользователе на страницу
    public User getCurrentUser(){
        return (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
    }

    // имеется ли роль у пользователя
    public boolean hasRole(String role){
        return getCurrentUser().getAuthorities().stream().filter(x -> x.getAuthority().equals("ROLE_"+role)).count()>0;
    }

    // сообщение пользователю, если аутентификация не прошла
    public String getLoginFailedMessage(){

        Object obj = FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("loginFailed");

        if (obj==null) return "";

        FacesContext context = FacesContext.getCurrentInstance();
        ResourceBundle bundle = context.getApplication().getResourceBundle(context, "msg");

        String message = bundle.getString("login_failed");
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().remove("loginFailed");
        if (Strings.isNullOrEmpty(message)){
            return "";
        }else{
            return message;
        }

    }



}

src/main/webapp/templates/part/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:o="http://omnifaces.org/ui"


>

<!-- нижняя часть страницы (подвал, футер)-->
<f:view>


    <footer class="footer-distributed">
        <div class="container">

            <div class="footer-left">


                <p class="footer-company-about" style="width: 70%; ">
                    <span>Онлайн библиотека на Spring 2.0 (2019 г.)</span>
                    Обучающий видеокурс JavaBegin (2019 г.) с использованием технологий: Spring Boot, Spring Data, Spring Security, Hibernate, JSF+Facelets, MySQL, Gradle

                </p>


            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Россия, г. Москва</span> ул. Тестовая, д. 50</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>+7 452 123456</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@javabegin.ru">support@javabegin.ru</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                    <span>О библиотеке</span>
                    Онлайн библиотека предназначена для поиска и просмотра книг по различным жанрам. Администраторы имеют возможность добавлять, удалять, редактировать.
                </p>

                <div class="footer-icons">

                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                    <a href="#"><i class="fa fa-github"></i></a>

                </div>

            </div>
        </div>

    </footer>


</f:view>
</html>

src/main/webapp/templates/part/locales.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:o="http://omnifaces.org/ui"

>

<!-- компоненты для переключения языка-->

<f:view>
    <div class="lang">

        <h:form>

            <div class="lang">


                <!-- для активной локали применяется css селектор active, чтобы показать рамку -->
                    <h:commandLink  actionListener="#{localeChanger.changeLocale('ru')}" value="#{msg.ru}" styleClass="#{localeChanger.currentLocale == 'ru' ? 'active':''} lang-link"/>

                    <h:commandLink  actionListener="#{localeChanger.changeLocale('en')}" value="#{msg.en}" styleClass="#{localeChanger.currentLocale == 'en' ? 'active':''} lang-link"/>


            </div>

        </h:form>


    </div>
</f:view>
</html>

src/main/webapp/templates/part/logout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"

      xmlns:p="http://primefaces.org/ui"

>

<!-- компоненты для выхода из системы-->
<f:view>
    <div style="float:right; width: 50%; text-align: right; ">


         <p:outputLabel value="#{msg.welcome}: #{userController.currentUser.username}"
                        style=" color:lightgray; font-size: 14px; font-weight: normal; padding-top: 15px;"/>
        <h:outputLink value="#{request.contextPath}/logout"
                      style="color:#dd993a; margin-left: 20px;">#{msg.logout}</h:outputLink>

    </div>
</f:view>
</html>